# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hospital.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hospital.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0ehospital.proto\"9\n\x06Person\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x11\n\tFirstName\x18\x02 \x01(\t\x12\x10\n\x08LastName\x18\x03 \x01(\t\"6\n\tParameter\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\x02\x12\x0c\n\x04Unit\x18\x03 \x01(\t\"o\n\x11\x45xaminationResult\x12\x0c\n\x04\x44\x61te\x18\x01 \x01(\t\x12\x13\n\x0b\x43ommisioner\x18\x02 \x01(\t\x12\x17\n\x06Person\x18\x03 \x01(\x0b\x32\x07.Person\x12\x1e\n\nParameters\x18\x04 \x03(\x0b\x32\n.Parameter\")\n\x17\x41\x64\x64\x45xaminationReturnMsg\x12\x0e\n\x06Retval\x18\x01 \x01(\x08\x32\x8a\x01\n\x08Hospital\x12@\n\x0e\x41\x64\x64\x45xamination\x12\x12.ExaminationResult\x1a\x18.AddExaminationReturnMsg\"\x00\x12<\n\x0eGetExamination\x12\x12.ExaminationResult\x1a\x12.ExaminationResult\"\x00\x30\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='Person.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FirstName', full_name='Person.FirstName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LastName', full_name='Person.LastName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=75,
)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='Parameter.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='Parameter.Value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Unit', full_name='Parameter.Unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=131,
)


_EXAMINATIONRESULT = _descriptor.Descriptor(
  name='ExaminationResult',
  full_name='ExaminationResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Date', full_name='ExaminationResult.Date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Commisioner', full_name='ExaminationResult.Commisioner', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Person', full_name='ExaminationResult.Person', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Parameters', full_name='ExaminationResult.Parameters', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=244,
)


_ADDEXAMINATIONRETURNMSG = _descriptor.Descriptor(
  name='AddExaminationReturnMsg',
  full_name='AddExaminationReturnMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Retval', full_name='AddExaminationReturnMsg.Retval', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=287,
)

_EXAMINATIONRESULT.fields_by_name['Person'].message_type = _PERSON
_EXAMINATIONRESULT.fields_by_name['Parameters'].message_type = _PARAMETER
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
DESCRIPTOR.message_types_by_name['ExaminationResult'] = _EXAMINATIONRESULT
DESCRIPTOR.message_types_by_name['AddExaminationReturnMsg'] = _ADDEXAMINATIONRETURNMSG

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'hospital_pb2'
  # @@protoc_insertion_point(class_scope:Person)
  ))
_sym_db.RegisterMessage(Person)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETER,
  __module__ = 'hospital_pb2'
  # @@protoc_insertion_point(class_scope:Parameter)
  ))
_sym_db.RegisterMessage(Parameter)

ExaminationResult = _reflection.GeneratedProtocolMessageType('ExaminationResult', (_message.Message,), dict(
  DESCRIPTOR = _EXAMINATIONRESULT,
  __module__ = 'hospital_pb2'
  # @@protoc_insertion_point(class_scope:ExaminationResult)
  ))
_sym_db.RegisterMessage(ExaminationResult)

AddExaminationReturnMsg = _reflection.GeneratedProtocolMessageType('AddExaminationReturnMsg', (_message.Message,), dict(
  DESCRIPTOR = _ADDEXAMINATIONRETURNMSG,
  __module__ = 'hospital_pb2'
  # @@protoc_insertion_point(class_scope:AddExaminationReturnMsg)
  ))
_sym_db.RegisterMessage(AddExaminationReturnMsg)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class HospitalStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.AddExamination = channel.unary_unary(
          '/Hospital/AddExamination',
          request_serializer=ExaminationResult.SerializeToString,
          response_deserializer=AddExaminationReturnMsg.FromString,
          )
      self.GetExamination = channel.unary_stream(
          '/Hospital/GetExamination',
          request_serializer=ExaminationResult.SerializeToString,
          response_deserializer=ExaminationResult.FromString,
          )


  class HospitalServicer(object):

    def AddExamination(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetExamination(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_HospitalServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'AddExamination': grpc.unary_unary_rpc_method_handler(
            servicer.AddExamination,
            request_deserializer=ExaminationResult.FromString,
            response_serializer=AddExaminationReturnMsg.SerializeToString,
        ),
        'GetExamination': grpc.unary_stream_rpc_method_handler(
            servicer.GetExamination,
            request_deserializer=ExaminationResult.FromString,
            response_serializer=ExaminationResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Hospital', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaHospitalServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def AddExamination(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetExamination(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaHospitalStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def AddExamination(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    AddExamination.future = None
    def GetExamination(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()


  def beta_create_Hospital_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Hospital', 'AddExamination'): ExaminationResult.FromString,
      ('Hospital', 'GetExamination'): ExaminationResult.FromString,
    }
    response_serializers = {
      ('Hospital', 'AddExamination'): AddExaminationReturnMsg.SerializeToString,
      ('Hospital', 'GetExamination'): ExaminationResult.SerializeToString,
    }
    method_implementations = {
      ('Hospital', 'AddExamination'): face_utilities.unary_unary_inline(servicer.AddExamination),
      ('Hospital', 'GetExamination'): face_utilities.unary_stream_inline(servicer.GetExamination),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Hospital_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Hospital', 'AddExamination'): ExaminationResult.SerializeToString,
      ('Hospital', 'GetExamination'): ExaminationResult.SerializeToString,
    }
    response_deserializers = {
      ('Hospital', 'AddExamination'): AddExaminationReturnMsg.FromString,
      ('Hospital', 'GetExamination'): ExaminationResult.FromString,
    }
    cardinalities = {
      'AddExamination': cardinality.Cardinality.UNARY_UNARY,
      'GetExamination': cardinality.Cardinality.UNARY_STREAM,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Hospital', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
